Repository microsoft/autogen, pull requests merged in 2023-10, with the labels that each got.

#50 retrieve_utils.py - Updated.py to have the ability to parse text from PDF Files
  autogen/retrieve_utils.py
  notebook/agentchat_RetrieveChat.ipynb
  setup.py
  test/test_files/example.pdf
  test/test_files/example.txt
  test/test_retrieve_utils.py
Labels: enhancement

#119 document about docker
  README.md
  autogen/agentchat/conversable_agent.py
  website/docs/Contribute.md
  website/docs/FAQ.md
  website/docs/Getting-Started.md
  website/docs/Installation.md
Labels: documentation

#263 Langchain tool bridge (#262)
  notebook/agentchat_langchain.ipynb
Labels: documentation

#278 TeachableAgent
  .github/workflows/openai.yml
  .gitignore
  autogen/agentchat/contrib/teachable_agent.py
  autogen/agentchat/contrib/text_analyzer_agent.py
  notebook/agentchat_teachability.ipynb
  setup.py
  test/agentchat/chat_with_teachable_agent.py
  test/agentchat/test_teachable_agent.py
  website/docs/Examples/AutoGen-AgentChat.md
  website/docs/Use-Cases/agent_chat.md
Labels: teach

#376 Add link to OptiGuide #371
  website/docs/Examples/AutoGen-AgentChat.md
  website/docs/Use-Cases/agent_chat.md
Labels: documentation

#383 api_base -> base_url
  OAI_CONFIG_LIST_sample
  autogen/oai/completion.py
  autogen/oai/openai_utils.py
  notebook/agentchat_MathChat.ipynb
  notebook/agentchat_RetrieveChat.ipynb
  notebook/agentchat_auto_feedback_from_code_execution.ipynb
  notebook/agentchat_chess.ipynb
  notebook/agentchat_groupchat.ipynb
  notebook/agentchat_groupchat_RAG.ipynb
  notebook/agentchat_groupchat_research.ipynb
  notebook/agentchat_groupchat_vis.ipynb
  notebook/agentchat_human_feedback.ipynb
  notebook/agentchat_planning.ipynb
  notebook/agentchat_stream.ipynb
  notebook/agentchat_teachability.ipynb
  notebook/agentchat_teaching.ipynb
  notebook/agentchat_two_users.ipynb
  notebook/agentchat_web_info.ipynb
  notebook/oai_chatgpt_gpt4.ipynb
  notebook/oai_completion.ipynb
  notebook/oai_openai_utils.ipynb
  setup.py
  test/oai/test_utils.py
  website/blog/2023-07-14-Local-LLMs/index.mdx
  website/docs/FAQ.md
  website/docs/Use-Cases/enhanced_inference.md
Labels: dependencies

#436 TeachableAgent blog post
  website/blog/2023-10-26-TeachableAgent/img/teachable-arch.png
  website/blog/2023-10-26-TeachableAgent/index.mdx
  website/blog/authors.yml
Labels: teach

#477 migration guide
  README.md
  autogen/oai/client.py
  autogen/oai/completion.py
  notebook/agentchat_qdrant_RetrieveChat.ipynb
  notebook/oai_openai_utils.ipynb
  website/blog/2023-10-26-TeachableAgent/index.mdx
  website/docs/Examples/AgentChat.md
  website/docs/Examples/Inference.md
  website/docs/Getting-Started.md
  website/docs/Installation.md
  website/docs/Use-Cases/agent_chat.md
  website/docs/Use-Cases/enhanced_inference.md
Labels: dependencies
