Repository microsoft/autogen, pull requests merged in 2024-03, with the labels that each got.

#1809 Add documentation for jupyter code executor
  autogen/coding/jupyter/base.py
  autogen/coding/jupyter/jupyter_client.py
  autogen/coding/jupyter/jupyter_code_executor.py
  autogen/coding/jupyter/local_jupyter_server.py
  website/.gitignore
  website/docs/topics/code-execution/_category_.json
  website/docs/topics/code-execution/jupyter-code-executor.ipynb
  website/process_notebooks.py
Labels: documentation, code-execution

#1884 Add annoucement bar for what's new blog post
  website/docusaurus.config.js
Labels: documentation

#1897 remove duplicated code
  samples/apps/autogen-studio/autogenstudio/utils/utils.py
Labels: studio

#1900 update description location
  samples/apps/autogen-studio/frontend/src/components/utils.ts
Labels: studio

#1908 Add warning and reorder jupyter executor docs
  website/docs/topics/code-execution/jupyter-code-executor.ipynb
Labels: documentation, code-execution

#1905 Fix broken links
  notebook/agentchat_teachability.ipynb
  website/blog/2023-10-26-TeachableAgent/index.mdx
Labels: bug, documentation

#1912 Adjusts send_introductions Type Hint in GroupChat
  autogen/agentchat/groupchat.py
Labels: dev

#1702 AutoGen Tutorial
  .pre-commit-config.yaml
  website/.gitattributes
  website/.gitignore
  website/docs/Getting-Started.md
  website/docs/Getting-Started.mdx
  website/docs/tutorial/assets/code-execution-in-conversation.png
  website/docs/tutorial/assets/code-executor-docker.png
  website/docs/tutorial/assets/code-executor-no-docker.png
  website/docs/tutorial/assets/conversable-agent.png
  website/docs/tutorial/assets/group-chat.png
  website/docs/tutorial/assets/human-in-the-loop.png
  website/docs/tutorial/assets/nested-chats.png
  website/docs/tutorial/assets/sequential-two-agent-chat.png
  website/docs/tutorial/assets/two-agent-chat.png
  website/docs/tutorial/code-executors.ipynb
  website/docs/tutorial/conversation-patterns.ipynb
  website/docs/tutorial/human-in-the-loop.ipynb
  website/docs/tutorial/introduction.ipynb
  website/docs/tutorial/termination.ipynb
  website/docs/tutorial/what-is-next.md
  website/process_notebooks.py
  website/sidebars.js
Labels: documentation

#1930 Fix remove -> remote
  website/docs/topics/code-execution/jupyter-code-executor.ipynb
Labels: documentation

#1934 Update introduction.ipynb
  website/docs/tutorial/introduction.ipynb
Labels: documentation

#1819 Made a configurable constant
  autogen/agentchat/groupchat.py
Labels: group chat

#1948 In code_utils.py, handling NotADirectoryError as well in get_powershell_command
  autogen/code_utils.py
Labels: code-execution

#1946 improve validation of llm_config
  autogen/agentchat/conversable_agent.py
  autogen/agentchat/groupchat.py
  autogen/agentchat/user_proxy_agent.py
  autogen/oai/client.py
  autogen/version.py
  notebook/agentchat_function_call_async.ipynb
  test/agentchat/test_conversable_agent.py
Labels: llm, alt-models

#1955 added new example in gallery.json
  website/src/data/gallery.json
  website/static/img/gallery/webagent.jpg
Labels: documentation

#1962 Rename tutorial chatper "Termination" to "Chat Termination"
  website/docs/tutorial/chat-termination.ipynb
  website/sidebars.js
Labels: documentation

#1655 Feature: Composable Actor Platform for AutoGen
  samples/apps/cap/README.md
  samples/apps/cap/TODO.md
  samples/apps/cap/c#/Readme.md
  samples/apps/cap/c++/Readme.md
  samples/apps/cap/node/Readme.md
  samples/apps/cap/py/autogencap/Actor.py
  samples/apps/cap/py/autogencap/ActorConnector.py
  samples/apps/cap/py/autogencap/Broker.py
  samples/apps/cap/py/autogencap/Config.py
  samples/apps/cap/py/autogencap/Constants.py
  samples/apps/cap/py/autogencap/DebugLog.py
  samples/apps/cap/py/autogencap/DirectorySvc.py
  samples/apps/cap/py/autogencap/LocalActorNetwork.py
  samples/apps/cap/py/autogencap/__init__.py
  samples/apps/cap/py/autogencap/ag_adapter/AG2CAP.py
  samples/apps/cap/py/autogencap/ag_adapter/AGActor.py
  samples/apps/cap/py/autogencap/ag_adapter/AutoGenConnector.py
  samples/apps/cap/py/autogencap/ag_adapter/CAP2AG.py
  samples/apps/cap/py/autogencap/ag_adapter/CAPGroupChat.py
  samples/apps/cap/py/autogencap/ag_adapter/CAPGroupChatManager.py
  samples/apps/cap/py/autogencap/ag_adapter/CAPPair.py
  samples/apps/cap/py/autogencap/ag_adapter/__init__.py
  samples/apps/cap/py/autogencap/proto/Autogen.proto
  samples/apps/cap/py/autogencap/proto/Autogen_pb2.py
  samples/apps/cap/py/autogencap/proto/Autogen_pb2.pyi
  samples/apps/cap/py/autogencap/proto/CAP.proto
  samples/apps/cap/py/autogencap/proto/CAP_pb2.py
  samples/apps/cap/py/autogencap/proto/CAP_pb2.pyi
  samples/apps/cap/py/autogencap/proto/__init__.py
  samples/apps/cap/py/autogencap/proto/proto-instructions.txt
  samples/apps/cap/py/autogencap/requirements.txt
  samples/apps/cap/py/autogencap/setup.py
  samples/apps/cap/py/demo/AGDemo.py
  samples/apps/cap/py/demo/AGGroupChatDemo.py
  samples/apps/cap/py/demo/App.py
  samples/apps/cap/py/demo/AppAgents.py
  samples/apps/cap/py/demo/CAPAutGenGroupDemo.py
  samples/apps/cap/py/demo/CAPAutoGenPairDemo.py
  samples/apps/cap/py/demo/ComplexActorDemo.py
  samples/apps/cap/py/demo/RemoteAGDemo.py
  samples/apps/cap/py/demo/SimpleActorDemo.py
  samples/apps/cap/py/demo/_paths.py
  samples/apps/cap/py/demo/standalone/Assistant.py
  samples/apps/cap/py/demo/standalone/Broker.py
  samples/apps/cap/py/demo/standalone/DirectorySvc.py
  samples/apps/cap/py/demo/standalone/UserProxy.py
  samples/apps/cap/py/demo/standalone/_paths.py
Labels: ui/deploy

#2027 Bump autogenbench version to 0.0.2
  samples/tools/autogenbench/autogenbench/version.py
Labels: autogenbench

#1907 [Feature] Adds Image Generation Capability 2.0
  .github/workflows/contrib-openai.yml
  .github/workflows/contrib-tests.yml
  autogen/agentchat/contrib/capabilities/generate_images.py
  notebook/agentchat_image_generation_capability.ipynb
  test/agentchat/contrib/capabilities/test_image_generation_capability.py
Labels: enhancement, multimodal, alt-models

#1801 Autogenstudio Updates [Upload/Dowload of Skills/Workflows, Streaming Agent Replies, Agent Message Summarization]
  .gitignore
  samples/apps/autogen-studio/Dockerfile
  samples/apps/autogen-studio/README.md
  samples/apps/autogen-studio/autogenstudio/chatmanager.py
  samples/apps/autogen-studio/autogenstudio/datamodel.py
  samples/apps/autogen-studio/autogenstudio/utils/dbdefaults.json
  samples/apps/autogen-studio/autogenstudio/utils/dbutils.py
  samples/apps/autogen-studio/autogenstudio/utils/utils.py
  samples/apps/autogen-studio/autogenstudio/version.py
  samples/apps/autogen-studio/autogenstudio/web/app.py
  samples/apps/autogen-studio/autogenstudio/workflowmanager.py
  samples/apps/autogen-studio/frontend/package.json
  samples/apps/autogen-studio/frontend/src/components/atoms.tsx
  samples/apps/autogen-studio/frontend/src/components/layout.tsx
  samples/apps/autogen-studio/frontend/src/components/types.ts
  samples/apps/autogen-studio/frontend/src/components/utils.ts
  samples/apps/autogen-studio/frontend/src/components/views/builder/agents.tsx
  samples/apps/autogen-studio/frontend/src/components/views/builder/models.tsx
  samples/apps/autogen-studio/frontend/src/components/views/builder/skills.tsx
  samples/apps/autogen-studio/frontend/src/components/views/builder/workflow.tsx
  samples/apps/autogen-studio/frontend/src/components/views/playground/chatbox.tsx
  samples/apps/autogen-studio/frontend/src/components/views/playground/metadata.tsx
  samples/apps/autogen-studio/frontend/src/components/views/playground/ra.tsx
  samples/apps/autogen-studio/frontend/src/components/views/playground/sessions.tsx
  samples/apps/autogen-studio/frontend/src/hooks/store.tsx
  samples/apps/autogen-studio/frontend/src/styles/global.css
  samples/apps/autogen-studio/notebooks/tutorial.ipynb
  samples/apps/autogen-studio/pyproject.toml
Labels: studio

#1938 Fix a initiate chats
  autogen/agentchat/chat.py
  notebook/agentchat_multi_task_async_chats.ipynb
Labels: async

#2052 Add docs about how to use docker for when autogen itself is run in docker
  website/docs/topics/code-execution/cli-code-executor.ipynb
  website/docs/topics/code-execution/jupyter-code-executor.ipynb
Labels: documentation

#2034 A11y: Enable tab-navigation on Card Grids
  samples/apps/autogen-studio/frontend/src/components/atoms.tsx
  samples/apps/autogen-studio/frontend/src/components/views/builder/agents.tsx
  samples/apps/autogen-studio/frontend/src/components/views/builder/models.tsx
  samples/apps/autogen-studio/frontend/src/components/views/builder/skills.tsx
  samples/apps/autogen-studio/frontend/src/components/views/builder/workflow.tsx
Labels: studio

#2091 Pin databind version to fix pydoc-markdown failure in CI
  .github/workflows/deploy-website.yml
Labels: dev

#2072 Add links to roadmap issues from README, Getting-Started, Contribute and Tutorial
  README.md
  website/docs/Contribute.md
  website/docs/Getting-Started.mdx
  website/docs/tutorial/what-next.md
Labels: documentation

#2054 Consolidate separate caching docs
  website/docs/Use-Cases/enhanced_inference.md
  website/docs/topics/llm-caching.md
Labels: documentation

#2094 Pin databind package versions in gh-release CI
  .github/workflows/deploy-website.yml
Labels: documentation

#2095 Simplify creating a new agent with custom reply function
  autogen/agentchat/contrib/gpt_assistant_agent.py
  autogen/agentchat/contrib/multimodal_conversable_agent.py
  autogen/agentchat/contrib/web_surfer.py
  autogen/agentchat/conversable_agent.py
Labels: bug

#2079 Add tool use chapter to tutorial
  website/docs/topics/task_decomposition.ipynb
  website/docs/tutorial/code-executors.ipynb
  website/docs/tutorial/tool-use.ipynb
  website/docs/tutorial/what-next.md
  website/sidebars.js
Labels: documentation

#2137 New conversational chess notebook using nested chats and tool use
  notebook/agentchat_chess.ipynb
  notebook/agentchat_nested_chats_chess.ipynb
  notebook/nested-chats-chess.png
  website/docs/Examples.md
  website/docs/tutorial/conversation-patterns.ipynb
  website/docs/tutorial/tool-use.ipynb
  website/docusaurus.config.js
Labels: documentation, function/tool, nested-chat

#2046 Parse Any HTML-esh Style Tags
  autogen/agentchat/contrib/img_utils.py
  autogen/agentchat/utils.py
  test/agentchat/test_agentchat_utils.py
Labels: dev

#1767 Integrate AgentOptimizer
  autogen/agentchat/contrib/agent_optimizer.py
  notebook/agentchat_agentoptimizer.ipynb
  test/agentchat/contrib/test_agent_optimizer.py
  website/blog/2023-12-23-AgentOptimizer/index.mdx
Labels: enhancement, function/tool, research

#2102 Implement User Defined Functions for Local CLI Executor
  .github/workflows/build.yml
  autogen/coding/func_with_reqs.py
  autogen/coding/local_commandline_code_executor.py
  setup.py
  test/coding/test_user_defined_functions.py
  website/docs/topics/code-execution/user-defined-functions.ipynb
Labels: code-execution

#2191 Add link for rendering notebooks docs on website
  website/docs/Contribute.md
Labels: documentation

#1923 Transform Messages Capability
  .github/workflows/contrib-tests.yml
  autogen/agentchat/contrib/capabilities/context_handling.py
  autogen/agentchat/contrib/capabilities/transform_messages.py
  autogen/agentchat/contrib/capabilities/transforms.py
  notebook/agentchat_capability_long_context_handling.ipynb
  notebook/agentchat_transform_messages.ipynb
  test/agentchat/contrib/capabilities/test_transform_messages.py
Labels: enhancement, long context handling, dev

#2174 AutoGenBench: Handle Ctrl-C more gracefully.
  samples/tools/autogenbench/autogenbench/run_cmd.py
  samples/tools/autogenbench/autogenbench/version.py
Labels: autogenbench

#2124 Fix `generate_init_message` for Multimodal Messages
  autogen/agentchat/conversable_agent.py
  test/agentchat/test_conversable_agent.py
Labels: multimodal
