Repository microsoft/autogen, pull requests merged in 2024-06, with the labels that each got.

#2843 Broken links fix
  notebook/JSON_mode_example.ipynb
  notebook/agentchat_agentoptimizer.ipynb
  notebook/agentchat_nested_chats_chess.ipynb
  website/docs/Examples.md
  website/docs/Use-Cases/agent_chat.md
  website/docs/installation/Optional-Dependencies.md
Labels: documentation

#2865 Bugfix: PGVector/RAG - Calculate the Vector Size based on Model Dimensions
  autogen/agentchat/contrib/vectordb/pgvectordb.py
  notebook/agentchat_pgvector_RetrieveChat.ipynb
  test/agentchat/contrib/retrievechat/test_pgvector_retrievechat.py
Labels: rag, vectordb

#2883 Improve update context condition checking rule
  autogen/agentchat/contrib/retrieve_user_proxy_agent.py
Labels: rag

#2937 update release log for AutoGen.Net 0.0.15
  dotnet/website/articles/toc.yml
  dotnet/website/update.md
Labels: AutoGen.Net

#2907 [Autobuild] improve robustness and reduce cost
  autogen/agentchat/contrib/agent_builder.py
  notebook/agent_library_example.json
  notebook/autobuild_agent_library.ipynb
  notebook/autobuild_basic.ipynb
  setup.py
  test/agentchat/contrib/example_agent_builder_library.json
  test/agentchat/contrib/example_test_agent_builder_config.json
  test/agentchat/contrib/test_agent_builder.py
  website/blog/authors.yml
Labels: dev, autobuilder

#2949 Client class utilities
  autogen/oai/client_utils.py
  test/oai/test_client_utils.py
Labels: alt-models

#2966 Function to indicate whether to hide tools for client_utils
  autogen/oai/client_utils.py
  test/oai/test_client_utils.py
Labels: alt-models

#2931 Anthropic Client
  .github/workflows/contrib-tests.yml
  autogen/logger/file_logger.py
  autogen/logger/sqlite_logger.py
  autogen/oai/anthropic.py
  autogen/oai/client.py
  autogen/runtime_logging.py
  autogen/token_count_utils.py
  setup.py
  test/oai/test_anthropic.py
  website/docs/topics/non-openai-models/cloud-anthropic.ipynb
Labels: function/tool, alt-models

#2892 Mistral Client
  .github/workflows/contrib-tests.yml
  autogen/logger/file_logger.py
  autogen/logger/sqlite_logger.py
  autogen/oai/client.py
  autogen/oai/client_utils.py
  autogen/oai/mistral.py
  autogen/runtime_logging.py
  autogen/token_count_utils.py
  setup.py
  test/oai/test_mistral.py
  website/docs/topics/non-openai-models/cloud-mistralai.ipynb
Labels: function/tool, alt-models

#2981 Anthropic client fixes
  autogen/oai/anthropic.py
  website/docs/topics/non-openai-models/cloud-anthropic.ipynb
Labels: alt-models

#2919 Together AI Client
  .github/workflows/contrib-tests.yml
  autogen/logger/file_logger.py
  autogen/logger/sqlite_logger.py
  autogen/oai/client.py
  autogen/oai/together.py
  autogen/runtime_logging.py
  setup.py
  test/oai/test_together.py
  website/docs/topics/non-openai-models/cloud-togetherai.ipynb
  website/docs/topics/non-openai-models/cloud-togetherai.md
Labels: alt-models

#2992 Fixed alternating message role bug in Anthropic client
  autogen/oai/anthropic.py
Labels: bug, alt-models

#2997 Anthropic Client - Handling multiple consecutive function calls
  autogen/oai/anthropic.py
Labels: alt-models

#3003 Groq Client
  .github/workflows/contrib-tests.yml
  autogen/logger/file_logger.py
  autogen/logger/sqlite_logger.py
  autogen/oai/client.py
  autogen/oai/groq.py
  autogen/runtime_logging.py
  setup.py
  test/oai/test_groq.py
Labels: alt-models

#3025 Update README.md
  autogen/agentchat/contrib/agent_eval/README.md
Labels: documentation
