Repository microsoft/autogen, pull requests merged in 2024-04, with the labels that each got.

#2248 Fix unstructured deps installation error
  .github/workflows/contrib-tests.yml
Labels: rag

#2250 Break up contributor guide for better navigability
  website/docs/Contribute.md
  website/docs/Getting-Started.mdx
  website/docs/contributor-guide/contributing.md
  website/docs/contributor-guide/docker.md
  website/docs/contributor-guide/documentation.md
  website/docs/contributor-guide/file-bug-report.md
  website/docs/contributor-guide/maintainer.md
  website/docs/contributor-guide/pre-commit.md
  website/docs/contributor-guide/tests.md
  website/docs/installation/Docker.md
  website/docs/tutorial/what-next.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: documentation

#2130 Multiline docstrings fix
  autogen/agentchat/chat.py
  autogen/agentchat/contrib/retrieve_user_proxy_agent.py
Labels: documentation

#2267 Re-commit of #2222: Expanded speaker name matching during speaker selection
  autogen/agentchat/groupchat.py
  test/agentchat/test_groupchat.py
Labels: group chat, alt-models

#2259 RetrieveUserProxyAgent, use context_max_tokens from retrieve_config if provided
  autogen/agentchat/contrib/retrieve_user_proxy_agent.py
Labels: rag

#2270 Remove subdirectory .gitattributes files and add relevant files to lfs
  test/test_files/test_image.png
  website/.gitattributes
  website/blog/2024-03-03-AutoGen-Update/img/.gitattributes
  website/static/img/gallery/composio-autogen.png
Labels: dev

#2281 Remove info log for IOStream using default.
  autogen/io/base.py
Labels: dev

#2271 Add html parser for RAG and some improvements
  autogen/retrieve_utils.py
  setup.py
  test/test_retrieve_utils.py
Labels: rag

#2324 Add back to top and year
  README.md
Labels: documentation

#2311 add support for Anthropic Claude function call
  website/docs/topics/non-openai-models/cloud-anthropic.ipynb
Labels: alt-models

#2144 Add "py" as lang in conversable agent (#1062)
  autogen/agentchat/conversable_agent.py
  autogen/code_utils.py
  autogen/coding/local_commandline_code_executor.py
  test/coding/test_commandline_code_executor.py
Labels: code-execution

#2393 Update chat-termination.ipynb
  website/docs/tutorial/chat-termination.ipynb
Labels: documentation

#2121 Code writing with a function call notebook created
  notebook/agentchat_function_call_code_writing.ipynb
  website/docs/Examples.md
Labels: documentation

#2390 DOCS: Add AutoTX to gallery
  website/src/data/gallery.json
  website/static/img/gallery/autotx.png
Labels: documentation

#2403 Fix function call notebook to make sure title is displayed.
  notebook/agentchat_function_call_code_writing.ipynb
Labels: documentation

#2369 add promptflow example
  samples/apps/promptflow-autogen/.gitignore
  samples/apps/promptflow-autogen/.promptflow/flow.tools.json
  samples/apps/promptflow-autogen/README.md
  samples/apps/promptflow-autogen/agentchat_nestedchat.py
  samples/apps/promptflow-autogen/autogen_stateflow.py
  samples/apps/promptflow-autogen/autogen_task.py
  samples/apps/promptflow-autogen/azure_openai.yaml
  samples/apps/promptflow-autogen/custom_conn.yaml
  samples/apps/promptflow-autogen/flow.dag.yaml
  samples/apps/promptflow-autogen/requirements.txt
  website/docs/ecosystem/img/ecosystem-promptflow.png
  website/docs/ecosystem/promptflow.md
Labels: documentation

#2366 Update the auto_feedback_from_code_execution notebook to use code executor
  .gitignore
  .pre-commit-config.yaml
  notebook/agentchat_agentoptimizer.ipynb
  notebook/agentchat_auto_feedback_from_code_execution.ipynb
  website/.gitignore
  website/docs/topics/code-execution/custom-executor.ipynb
Labels: documentation, code-execution

#2426 support openai 'sk-proj-' apikey format
  autogen/oai/openai_utils.py
  test/oai/test_utils.py
Labels: oai_config_list

#2436 Add Git LFS check action, fix broken lfs files
  .github/workflows/lfs-check.yml
  website/docs/ecosystem/img/ecosystem-promptflow.png
  website/static/img/gallery/autotx.png
Labels: dev

#2071 Use latest APIs for tool use, code execution and cache in topic pages
  website/docs/topics/prompting-and-reasoning/react.ipynb
  website/docs/topics/prompting-and-reasoning/reflection.ipynb
  website/docs/topics/task_decomposition.ipynb
Labels: documentation, code-execution, function/tool

#2439 [Re-Opened] Support for PGVector Database in Autogen
  .github/workflows/contrib-openai.yml
  .github/workflows/contrib-tests.yml
  autogen/agentchat/contrib/vectordb/base.py
  autogen/agentchat/contrib/vectordb/pgvectordb.py
  notebook/agentchat_pgvector_RetrieveChat.ipynb
  notebook/agentchat_qdrant_RetrieveChat.ipynb
  setup.py
  test/agentchat/contrib/test_pgvector_retrievechat.py
  test/agentchat/contrib/vectordb/test_pgvectordb.py
  website/docs/ecosystem/pgvector.md
  website/docs/installation/Optional-Dependencies.md
  website/docs/topics/retrieval_augmentation.md
Labels: vectordb

#2464 Add support for HTML, CSS and Javascript in LocalCommandLineCodeExecutor with Mapping executor/saver #2303
  autogen/coding/local_commandline_code_executor.py
  autogen/coding/utils.py
  test/coding/test_commandline_code_executor.py
Labels: code-execution

#2504 fix: `autogen.AssistantAgent` at https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat/
  website/blog/2023-10-18-RetrieveChat/index.mdx
Labels: documentation

#2455 2447 fix pgvector tests and notebook
  .github/workflows/contrib-openai.yml
  .github/workflows/contrib-tests.yml
  autogen/agentchat/contrib/vectordb/pgvectordb.py
  notebook/agentchat_RetrieveChat.ipynb
  notebook/agentchat_function_call_code_writing.ipynb
  notebook/agentchat_pgvector_RetrieveChat.ipynb
  setup.py
  test/agentchat/contrib/retrievechat/test_pgvector_retrievechat.py
  test/agentchat/contrib/retrievechat/test_qdrant_retrievechat.py
  test/agentchat/contrib/retrievechat/test_retrievechat.py
  test/agentchat/contrib/vectordb/test_pgvectordb.py
Labels: bug, rag, vectordb

#2304 Re-query speaker name when multiple speaker names returned during Group Chat speaker selection
  autogen/agentchat/conversable_agent.py
  autogen/agentchat/groupchat.py
  test/agentchat/test_groupchat.py
Labels: group chat, alt-models
