Repository microsoft/autogen, pull requests merged in 2024-01, with the labels that each got.

#1082 [Core] Throw an error when the OAI_CONFIG_LIST is missing.
  autogen/oai/openai_utils.py
  test/agentchat/contrib/test_compressible_agent.py
  test/agentchat/contrib/test_gpt_assistant.py
  test/oai/test_utils.py
Labels: bug

#1145 [Core] check if docker is installed if user_docker is specified.
  autogen/code_utils.py
Labels: code-execution, docker

#1072 Remove GPT-4 as the default model.
  OAI_CONFIG_LIST_sample
  README.md
  autogen/agentchat/conversable_agent.py
  test/agentchat/test_conversable_agent.py
Labels: robustness

#1039 [AutoBuild] Supporting build agents from library; supporting generating agent descriptions
  .github/workflows/contrib-openai.yml
  autogen/agentchat/contrib/agent_builder.py
  notebook/agent_library_example.json
  notebook/agentchat_autobuild.ipynb
  notebook/autobuild_agent_library.ipynb
  notebook/autobuild_basic.ipynb
  setup.py
  test/agentchat/contrib/example_agent_builder_library.json
  test/agentchat/contrib/example_test_agent_builder_config.json
  test/agentchat/contrib/test_agent_builder.py
  website/blog/2023-11-26-Agent-AutoBuild/index.mdx
  website/docs/Examples.md
Labels: autobuilder

#1111 guide on the usage of docker
  README.md
  samples/dockers/Dockerfile.base
  samples/dockers/Dockerfile.dev
  samples/dockers/Dockerfile.full
  website/docs/Contribute.md
  website/docs/FAQ.md
  website/docs/Installation.md
Labels: docker

#1118 Handle streamed function calls
  autogen/oai/client.py
Labels: function

#1185 Documentation: polish docs for tools calls
  notebook/agentchat_function_call_currency_calculator.ipynb
  website/docs/Use-Cases/agent_chat.md
Labels: documentation

#1190 remove inappropriate api_type
  autogen/oai/openai_utils.py
Labels: documentation, oai_config_list

#1204 More async tool fixes
  autogen/agentchat/conversable_agent.py
Labels: bug, async

#1101 Upgrade docusaurus
  .github/workflows/deploy-website.yml
  autogen/oai/completion.py
  scripts/docs_build.sh
  scripts/docs_serve.sh
  website/blog/2023-04-21-LLM-tuning-math/index.md
  website/blog/2023-07-14-Local-LLMs/index.md
  website/docs/Use-Cases/enhanced_inference.md
  website/docusaurus.config.js
  website/package.json
  website/pydoc-markdown.yml
  website/sidebars.js
  website/yarn.lock
Labels: documentation

#1127 [Core] Sanitize filename before using it as docker image tag. Fix #1069
  autogen/code_utils.py
  test/test_code.py
Labels: code-execution, docker

#1227 [Core] Compatibility with function call style API (Azure OpenAI and Gemini)
  autogen/agentchat/conversable_agent.py
  test/agentchat/test_conversable_agent.py
  test/agentchat/test_tool_calls.py
  website/docs/Use-Cases/agent_chat.md
Labels: function

#951 Refined the user_proxy description.
  autogen/agentchat/user_proxy_agent.py
Labels: gaia

#1226 Added the ability to add tags to the OAI_CONFIG_LIST, and filter
  autogen/oai/client.py
  autogen/oai/openai_utils.py
  test/oai/test_utils.py
Labels: oai_config_list

#1301 Chore: Updated Blog and removed `cd frontend`
  website/blog/2023-12-01-AutoGenStudio/index.mdx
Labels: documentation, ui/deploy

#1254 def _prepare_chat for groupchat manager to reset the groupchat
  autogen/agentchat/conversable_agent.py
  autogen/agentchat/groupchat.py
  notebook/agentchat_function_call_async.ipynb
Labels: group chat

#1147 set use_docker to default to True
  .github/workflows/build.yml
  .github/workflows/contrib-tests.yml
  README.md
  autogen/agentchat/conversable_agent.py
  autogen/agentchat/user_proxy_agent.py
  autogen/code_utils.py
  notebook/agentchat_auto_feedback_from_code_execution.ipynb
  notebook/agentchat_compression.ipynb
  notebook/agentchat_function_call.ipynb
  notebook/agentchat_groupchat.ipynb
  notebook/agentchat_groupchat_research.ipynb
  notebook/agentchat_groupchat_vis.ipynb
  notebook/agentchat_guidance.ipynb
  notebook/agentchat_human_feedback.ipynb
  notebook/agentchat_langchain.ipynb
  notebook/agentchat_lmm_gpt-4v.ipynb
  notebook/agentchat_lmm_llava.ipynb
  notebook/agentchat_microsoft_fabric.ipynb
  notebook/agentchat_oai_assistant_function_call.ipynb
  notebook/agentchat_oai_assistant_groupchat.ipynb
  notebook/agentchat_oai_assistant_twoagents_basic.ipynb
  notebook/agentchat_oai_code_interpreter.ipynb
  notebook/agentchat_planning.ipynb
  notebook/agentchat_teachability.ipynb
  notebook/agentchat_teachable_oai_assistants.ipynb
  notebook/agentchat_two_users.ipynb
  notebook/agentchat_video_transcript_translate_with_whisper.ipynb
  notebook/agentchat_web_info.ipynb
  notebook/agenteval_cq_math.ipynb
  setup.py
  test/agentchat/test_agent_setup_with_use_docker_settings.py
  test/test_code.py
  test/twoagent.py
  website/docs/FAQ.md
  website/docs/Getting-Started.md
  website/docs/Installation.md
Labels: code-execution, docker

#1241 Add dev container for AutoGen Studio
  .devcontainer/studio/Dockerfile
  .devcontainer/studio/devcontainer.json
Labels: ui/deploy

#1222 [Core] implement redis cache mode
  .github/workflows/build.yml
  .github/workflows/openai.yml
  autogen/agentchat/conversable_agent.py
  autogen/agentchat/groupchat.py
  autogen/cache/__init__.py
  autogen/cache/abstract_cache_base.py
  autogen/cache/cache.py
  autogen/cache/cache_factory.py
  autogen/cache/disk_cache.py
  autogen/cache/redis_cache.py
  autogen/oai/client.py
  setup.py
  test/agentchat/test_cache_agent.py
  test/cache/test_cache.py
  test/cache/test_disk_cache.py
  test/cache/test_redis_cache.py
  test/conftest.py
  test/oai/test_client.py
  website/docs/Installation.md
  website/docs/Use-Cases/agent_chat.md
  website/docs/Use-Cases/enhanced_inference.md
Labels: enhancement, integration

#1291 More documentation for Cache. Updated FAQ to include database Locked error
  autogen/oai/__init__.py
  website/docs/FAQ.md
  website/docs/Use-Cases/agent_chat.md
  website/docs/Use-Cases/enhanced_inference.md
Labels: documentation

#1093 Add a web surfer agent that can search and browse the web.
  .github/workflows/contrib-openai.yml
  .github/workflows/contrib-tests.yml
  autogen/agentchat/contrib/web_surfer.py
  autogen/browser_utils.py
  notebook/agentchat_surfer.ipynb
  setup.py
  test/agentchat/contrib/test_web_surfer.py
  test/test_browser_utils.py
  website/docs/Examples.md
Labels: gaia

#1348 Add an AutoGen UI example powered by Panel
  website/src/data/gallery.json
Labels: documentation

#1333 Cleanup and unify Dockerfiles
  .devcontainer/README.md
  .devcontainer/dev/Dockerfile
  .devcontainer/dev/devcontainer.json
  .devcontainer/full/Dockerfile
  .devcontainer/full/devcontainer.json
  samples/dockers/Dockerfile.base
  website/docs/Contribute.md
  website/docs/Installation.md
Labels: documentation, dev

#1230 functionality of manual history cleaning by user proxy added
  autogen/agentchat/conversable_agent.py
  autogen/agentchat/groupchat.py
  test/agentchat/test_groupchat.py
Labels: group chat, long context handling

#1459 Prints the version of AutoGenBench from the command line, closing i1458
  samples/tools/autogenbench/autogenbench/cli.py
  samples/tools/autogenbench/autogenbench/run_cmd.py
  samples/tools/autogenbench/autogenbench/template/testbed_utils.py
Labels: autogenbench

#1451 FAQ, working with LLM endpoints and explaining why config-list is a list
  notebook/oai_openai_utils.ipynb
  website/docs/FAQ.md
Labels: documentation, oai_config_list, alt-models

#890 Adds a SocietyOfMindAgent that presents as a single agent, but runs GroupChat as an inner-monologue
  autogen/agentchat/contrib/society_of_mind_agent.py
  notebook/agentchat_society_of_mind.ipynb
  test/agentchat/contrib/test_society_of_mind_agent.py
  website/docs/Examples.md
Labels: group chat, gaia

#1482 Initial PR: Add gitignore and improve template detection
  samples/tools/autogenbench/.gitignore
  samples/tools/autogenbench/scenarios/GAIA/Scripts/init_tasks.py
Labels: gaia

#1485 Bump autogenbench version.
  samples/tools/autogenbench/autogenbench/version.py
Labels: autogenbench
