Repository microsoft/autogen, pull requests merged in 2024-10, with the labels that each got.

#3056 Ollama Client (with tool calling)
  .github/workflows/contrib-tests.yml
  autogen/logger/file_logger.py
  autogen/logger/sqlite_logger.py
  autogen/oai/client.py
  autogen/oai/ollama.py
  autogen/runtime_logging.py
  setup.py
  test/oai/test_ollama.py
  website/docs/topics/non-openai-models/local-ollama.ipynb
Labels: alt-models

#3593 Ollama library v0.3.3 update with changes to options handling
  autogen/oai/ollama.py
  setup.py
  test/oai/test_ollama.py
Labels: alt-models

#3726 Function Calling Support for Gemini - Part 2
  autogen/oai/gemini.py
  autogen/oai/openai_utils.py
  notebook/agentchat_gemini.ipynb
  test/oai/test_gemini.py
Labels: 0.2

#2696 Fix #2643 - groupchat model registration
  autogen/agentchat/groupchat.py
  test/agentchat/test_groupchat.py
  website/docs/topics/groupchat/using_custom_models.md
Labels: group chat, 0.2, awaiting-op-response

#3461 Added a demonstartion notebook featuring the usage of Langchain with AutoGen
  notebook/agentchat_huggingface_langchain.ipynb
Labels: 0.2, awaiting-op-response

#3238 Autobuild Function calling
  autogen/agentchat/contrib/agent_builder.py
  notebook/autobuild_function_calling.ipynb
  test/agentchat/contrib/test_agent_builder.py
Labels: 0.2, awaiting-op-response

#2720 Notebook on web crawling
  notebook/agentchat_webcrawling_with_spider.ipynb
  website/docs/Examples.md
Labels: 0.2

#3732 Support structured output
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/cookbook/index.md
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/cookbook/structured-output-agent.ipynb
  python/packages/autogen-core/src/autogen_core/components/models/_openai_client.py
Labels: awaiting-op-response

#3776 Fix broken image URL in README
  README.md
Labels: 0.2

#3775 Clarify stable package name and version on home page
  website/src/pages/index.js
Labels: 0.2

#3778 Create a notebook to demonstrate handoff pattern
  python/packages/autogen-core/docs/drawio/handoffs.drawio
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/core-concepts/application-stack.md
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/design-patterns/handoffs.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/design-patterns/handoffs.svg
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/design-patterns/index.md
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/design-patterns/multi-agent-design-patterns.md
Labels: proj-core

#3813 Create Semantic Router example
  python/packages/autogen-core/samples/semantic_router/README.md
  python/packages/autogen-core/samples/semantic_router/_agents.py
  python/packages/autogen-core/samples/semantic_router/_semantic_router_agent.py
  python/packages/autogen-core/samples/semantic_router/_semantic_router_components.py
  python/packages/autogen-core/samples/semantic_router/run_host.py
  python/packages/autogen-core/samples/semantic_router/run_semantic_router.py
Labels: awaiting-op-response, example-app

#3296 [CAP] Abstraction of actor_connector to go along with runtime factory and runtime abstraction
  samples/apps/cap/py/autogencap/Config.py
  samples/apps/cap/py/autogencap/actor.py
  samples/apps/cap/py/autogencap/actor_connector.py
  samples/apps/cap/py/autogencap/actor_runtime.py
  samples/apps/cap/py/autogencap/ag_adapter/AGActor.py
  samples/apps/cap/py/autogencap/ag_adapter/ag_actor.py
  samples/apps/cap/py/autogencap/ag_adapter/ag_to_cap.py
  samples/apps/cap/py/autogencap/ag_adapter/agent.py
  samples/apps/cap/py/autogencap/ag_adapter/autogen_connector.py
  samples/apps/cap/py/autogencap/ag_adapter/cap_group_chat.py
  samples/apps/cap/py/autogencap/ag_adapter/cap_group_chat_manager.py
  samples/apps/cap/py/autogencap/ag_adapter/cap_pair.py
  samples/apps/cap/py/autogencap/ag_adapter/cap_to_ag.py
  samples/apps/cap/py/autogencap/broker.py
  samples/apps/cap/py/autogencap/debug_log.py
  samples/apps/cap/py/autogencap/runtime_factory.py
  samples/apps/cap/py/autogencap/utility.py
  samples/apps/cap/py/autogencap/zmq_actor_connector.py
  samples/apps/cap/py/autogencap/zmq_directory_svc.py
  samples/apps/cap/py/autogencap/zmq_msg_receiver.py
  samples/apps/cap/py/autogencap/zmq_runtime.py
  samples/apps/cap/py/demo/ag_demo.py
  samples/apps/cap/py/demo/ag_group_chat_demo.py
  samples/apps/cap/py/demo/app.py
  samples/apps/cap/py/demo/app_agents.py
  samples/apps/cap/py/demo/cap_autogen_group_demo.py
  samples/apps/cap/py/demo/cap_autogen_pair_demo.py
  samples/apps/cap/py/demo/complex_actor_demo.py
  samples/apps/cap/py/demo/list_agents.py
  samples/apps/cap/py/demo/remote_autogen_demo.py
  samples/apps/cap/py/demo/simple_actor_demo.py
  samples/apps/cap/py/demo/single_threaded.py
  samples/apps/cap/py/demo/standalone/UserProxy.py
  samples/apps/cap/py/demo/standalone/assistant.py
  samples/apps/cap/py/demo/standalone/broker.py
  samples/apps/cap/py/demo/standalone/directory_svc.py
  samples/apps/cap/py/demo/standalone/user_proxy.py
  samples/apps/cap/py/demo/zmq_tests.py
Labels: 0.2, awaiting-op-response

#3848 migrate models
  README.md
  python/packages/agbench/benchmarks/AssistantBench/Templates/MagenticOne/scenario.py
  python/packages/agbench/benchmarks/GAIA/Templates/MagenticOne/scenario.py
  python/packages/agbench/benchmarks/HumanEval/Templates/MagenticOne/scenario.py
  python/packages/agbench/benchmarks/WebArena/Templates/MagenticOne/scenario.py
  python/packages/autogen-agentchat/tests/test_group_chat.py
  python/packages/autogen-core/docs/src/packages/index.md
  python/packages/autogen-core/docs/src/user-guide/agentchat-user-guide/examples/company-research.ipynb
  python/packages/autogen-core/docs/src/user-guide/agentchat-user-guide/examples/literature-review.ipynb
  python/packages/autogen-core/docs/src/user-guide/agentchat-user-guide/examples/travel-planning.ipynb
  python/packages/autogen-core/docs/src/user-guide/agentchat-user-guide/tutorial/selector-group-chat.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/cookbook/azure-openai-with-aad-auth.md
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/cookbook/structured-output-agent.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/cookbook/tool-use-with-intervention.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/design-patterns/group-chat.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/design-patterns/handoffs.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/design-patterns/reflection.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/framework/model-clients.ipynb
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/quickstart.ipynb
  python/packages/autogen-core/src/autogen_core/components/models/__init__.py
  python/packages/autogen-ext/pyproject.toml
  python/packages/autogen-ext/src/autogen_ext/code_executors/_azure_container_code_executor.py
  python/packages/autogen-ext/src/autogen_ext/code_executors/_docker_code_executor.py
  python/packages/autogen-ext/src/autogen_ext/models/__init__.py
  python/packages/autogen-ext/src/autogen_ext/models/_openai/_model_info.py
  python/packages/autogen-ext/src/autogen_ext/models/_openai/_openai_client.py
  python/packages/autogen-ext/src/autogen_ext/models/_openai/config/__init__.py
  python/packages/autogen-ext/src/autogen_ext/tools/_langchain_adapter.py
  python/packages/autogen-ext/tests/models/test_openai_model_client.py
  python/packages/autogen-magentic-one/pyproject.toml
  python/packages/autogen-magentic-one/src/autogen_magentic_one/utils.py
  python/pyproject.toml
  python/uv.lock
Labels: proj-extensions, awaiting-op-response

#3842 Multiversion docs build
  .github/workflows/docs.yml
  docs/switcher.json
  python/packages/autogen-core/docs/src/_static/override-switcher-button.js
  python/packages/autogen-core/docs/src/conf.py
Labels: documentation

#3949 Refactor agent chat to prepare for handoff/swarm
  python/packages/autogen-agentchat/src/autogen_agentchat/agents/__init__.py
  python/packages/autogen-agentchat/src/autogen_agentchat/agents/_base_chat_agent.py
  python/packages/autogen-agentchat/src/autogen_agentchat/agents/_tool_use_assistant_agent.py
  python/packages/autogen-agentchat/src/autogen_agentchat/base/__init__.py
  python/packages/autogen-agentchat/src/autogen_agentchat/base/_chat_agent.py
  python/packages/autogen-agentchat/src/autogen_agentchat/logging/_console_log_handler.py
  python/packages/autogen-agentchat/src/autogen_agentchat/logging/_file_log_handler.py
  python/packages/autogen-agentchat/src/autogen_agentchat/messages.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/__init__.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_events.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_base_chat_agent_container.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_base_group_chat.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_base_group_chat_manager.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_chat_agent_container.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_round_robin_group_chat.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_selector_group_chat.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_swarm_group_chat.py
  python/packages/autogen-agentchat/tests/test_group_chat.py
  python/packages/autogen-agentchat/tests/test_tool_use_assistant_agent.py
Labels: proj-agentchat

#3759 Add sample distributed group chat notebook
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/framework/distributed-agent-runtime.ipynb
  python/packages/autogen-core/samples/distributed-group-chat/.gitattributes
  python/packages/autogen-core/samples/distributed-group-chat/README.md
  python/packages/autogen-core/samples/distributed-group-chat/_agents.py
  python/packages/autogen-core/samples/distributed-group-chat/_types.py
  python/packages/autogen-core/samples/distributed-group-chat/_utils.py
  python/packages/autogen-core/samples/distributed-group-chat/config.yaml
  python/packages/autogen-core/samples/distributed-group-chat/run.sh
  python/packages/autogen-core/samples/distributed-group-chat/run_editor_agent.py
  python/packages/autogen-core/samples/distributed-group-chat/run_group_chat_manager.py
  python/packages/autogen-core/samples/distributed-group-chat/run_host.py
  python/packages/autogen-core/samples/distributed-group-chat/run_writer_agent.py
Labels: awaiting-op-response, example-app

#3968 Ability to generate handoff message from AssistantAgent
  python/packages/autogen-agentchat/src/autogen_agentchat/agents/__init__.py
  python/packages/autogen-agentchat/src/autogen_agentchat/agents/_assistant_agent.py
  python/packages/autogen-agentchat/src/autogen_agentchat/messages.py
  python/packages/autogen-agentchat/src/autogen_agentchat/teams/_group_chat/_swarm_group_chat.py
  python/packages/autogen-agentchat/tests/test_assistant_agent.py
  python/packages/autogen-agentchat/tests/test_group_chat.py
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/framework/model-clients.ipynb
Labels: proj-agentchat

#3977 Run LocalCommandLineCodeExecutor within venv
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/framework/command-line-code-executors.ipynb
  python/packages/autogen-core/src/autogen_core/components/code_executor/_impl/local_commandline_code_executor.py
  python/packages/autogen-core/tests/execution/test_commandline_code_executor.py
Labels: code-execution

#3972 Fix: provide valid Prompt and Completion Token usage counts from create_stream
  python/packages/autogen-core/docs/src/user-guide/core-user-guide/framework/model-clients.ipynb
  python/packages/autogen-core/src/autogen_core/components/models/_openai_client.py
  python/packages/autogen-ext/src/autogen_ext/models/_openai/_openai_client.py
  python/packages/autogen-ext/tests/models/test_openai_model_client.py
Labels: proj-extensions
